### PR TITLE
Repository 'listCommits' working when options omitted

### LINKED ISSUE #508: Repository `listCommits` does not call callback if options are omitted
# Expected Behaviour
Calling `listCommits` on a `Repository` should execute the callback even when no options are given. According to [the function's documentation](http://github-tools.github.io/github/docs/3.0.0/Repository.html#listCommits), the `options` are optional (unlike, for example, the `options` of [`listPullRequests`](http://github-tools.github.io/github/docs/3.0.0/Repository.html#listPullRequests)).

# Actual Behaviour
Calling `listCommits` on a `Repository` without giving an options object results in the callback *not* being called, even when the `Promise` is fulfilled.

# Steps to Reproduce the Problem
I have reduced my own code to the following minimal working example:
```html
<!DOCTYPE html>
<html>
    <body>
        <script src="https://unpkg.com/github-api/dist/GitHub.bundle.min.js"></script>
        <script>
            var gh = new GitHub();

            var repo = gh.getRepo("github-tools", "github");
            repo.listCommits(function() {
                alert("Callback was called.");
            });
        </script>
    </body>
</html>
```
I observed that there was no alert.

In order to verify that the issue was indeed with the lack of options and not with my setup, I changed the above code to include an empty options object:
```html
<!DOCTYPE html>
<html>
    <body>
        <script src="https://unpkg.com/github-api/dist/GitHub.bundle.min.js"></script>
        <script>
            var gh = new GitHub();

            var repo = gh.getRepo("github-tools", "github");
            repo.listCommits({}, function() {
                alert("Callback was called.");
            });
        </script>
    </body>
</html>
```
This time around I *did* receive an alert.

# Specifications
* **Version**: 3.0.0
* **Operating system**: Windows 10 (64 bit)
* **Browser**: Google Chrome, version 66.0.3359.139 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by WJXHenry**
Fixes #508.

This PR resolves the issue of having to explicitly specify the options parameter. I also changed the existing test to properly validate a 'listCommits' function call without options.

### CODE REVIEW

File: lib/Repository.js [hunk 1]
```diff
@@ -187,8 +187,10 @@ class Repository extends Requestable {
     * @return {Promise} - the promise for the http request
     */
    listCommits(options, cb) {
-      options = options || {};
-
+      if (typeof options === 'function') {
```
Comment (j-rewerts) [inline lib/Repository.js]: It looks like the options object is not considered optional according to the JS docs. I think it's also worth thinking about existing users, so we don't change the interface for them going forwards without a major semantic version increase.
I think if you include both the default value setting of `options = options || {};` as well as the callback code, it should work for both situations. Also update the Jsdoc comments to mark options as optional.

Comment (WJXHenry) [reply lib/Repository.js]: I added the original functionality back along with the new code. The options parameter is already marked as optional in the [JSDocs](http://github-tools.github.io/github/docs/3.1.0/Repository.html#listCommits).

**Comment by j-rewerts** [comment]
LGTM. Thanks @WJXHenry .
